import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NextThemeProvider from "../Providers/NextThemeProvider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import Loader from "@/components/ui/Loader";
import { Suspense } from "react";
import ToastProvider from "@/Providers/ToastProvider";
import StoreProvider from "@/Providers/StoreProvider";
import AuthProvider from "@/Providers/AuthProvider";
import LangaugeProvider from "@/Providers/LangaugeProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Include the font weights you need
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} relative antialiased flex flex-col justify-between min-h-screen items-center`}
      >
        <div className="fixed w-[30vw] mx-auto aspect-square bg-gradient-to-br from-sky-400 to-transparent rounded-full blur-3xl opacity-60 z-[-11]"></div>

        <NextThemeProvider>
          <AuthProvider>
            <StoreProvider>
              <LangaugeProvider>
                <Header />
                <Suspense fallback={<Loader />}>{children}</Suspense>
                <ToastProvider />
                <Footer />
              </LangaugeProvider>
            </StoreProvider>
          </AuthProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
